### ISSUE TITLE
277行改成 ip = request.urlopen('https://api.ip.sb/ip').readline()，要不然报错

### ISSUE THREAD

**Issue by Mpk2022** [doudoudzj/vpsmate#39]
def detect_ip(self):
        ip = request.urlopen('https://api.ip.sb/ip').readline()
        return ip

**Comment by Clancy6** [comment]
已经暴雷了：
```
Traceback (most recent call last):
  File "install.py", line 392, in <module>
    install.install()
  File "install.py", line 381, in install
    print('\033[4;34mhttp://%s:%s/\033[0m' % (self.detect_ip(), self.listen_port))
  File "install.py", line 277, in detect_ip
    ip = request.urlopen('http://ip.42.pl/raw').readline()
……
socket.error: [Errno 104] Connection reset by peer
```

**Comment by jksdou** [comment]
@Clancy6 好的
